[package]
name = "karoowa-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Karoowa Sparse Merkle Trie — cryptographic state commitment"

[dependencies]
karoowa-crypto = { workspace = true }

serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
