[package]
name = "karoowa-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Karoowa core primitives — block, transaction, state, receipt, config, license gate"

[dependencies]
karoowa-crypto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
